name             'bitmonk_runit_wtf'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures bitmonk_runit_wtf'
long_description 'Installs/Configures bitmonk_runit_wtf'
version          '0.1.0'
